### ISSUE TITLE
isUserAdmin logic is incorrect

### ISSUE THREAD

**Issue by Speewack** [Speewack/wlts-import#7]
In Main.java, the logic for isUserAdmin pulls the first unit result from the ["current-user-detail" endpoint](https://www.lds.org/mobiledirectory/services/v2/ldstools/current-user-detail).
This is incorrect as the resulting json may contain multiple units (ward, stake, etc).
Mine seems to return all units in the stake (Stake, plus multiple wards and a branch)
Logic should be to pull the homeUnitNbr attribute, then check for admin on that unit number in the included array of units.

**Comment by marcpage** [comment]
Mine shows one unit (our stake) and then has a list of local units. I assume you are seeing false for the stake hasUnitAdminRights, but your unit has true for hasUnitAdminRights under localUnits. Is that correct? It might be easier if I could see the output of your current-user-detail ( https://www.lds.org/mobiledirectory/services/v2/ldstools/current-user-detail ). Could you get that to me out of band?
